### ISSUE TITLE
How did you get 1500+ GitHub stars?

### ISSUE THREAD

**Issue by dandv** [kumailht/flakes#29]
Congratulations on Flakes - it looks clean, simple and nice; and it's lighter than Bootstrap. I like the clear positioning for internal apps, and on the light end of the spectrum, vs. UI component libraries like [Webix](http://webix.com), ExtJS or Kendo.

But having in mind that Flakes is only [three months old](https://github.com/kumailht/flakes/commits/master) and has only ~20 commits, how did you manage to get 1500 GitHub stars?

Webix by comparison, while [also on GitHub](https://github.com/webix-hub/tracker/issues/149), has under 20 stars, despite offering a far wider array of UI widgets, and having launched in July 2013.

**Comment by kardianos** [comment]
This isn't the best place to discuss, but as this bug is still open...

License is everything. I've created several times application specific variants of what webix can do. I'd love to use something like webix, but if I have to choose between writing code that does what I want, or a black box that I can't modify (commercial license), I'm going to choose write my own code. If you're targeting business users, seeing the GPL, especially v3, is a deal breaker. At first I didn't even see your commercial offering.

The only products large enough to "pay" for closed source are database engines. And they have a "standard" interface. A black box UI kit. Not worth the long term support cost as the application evolves.
