### ISSUE TITLE
Empty space on the right

### ISSUE THREAD

**Issue by rrader** [kumailht/flakes#48]
Hi
Is there a clean way to get flakes span over 100% width of the browser? I have 1920 screen and have an empty space on the right

![screenshot from 2017-01-28 11-59-05](https://cloud.githubusercontent.com/assets/300061/22395824/ffdc2552-e551-11e6-86d4-8b9f9e832f4c.png)

**Comment by kumailht** [comment]
@rrader Flakes was designed to read like a book, left to right. It's hard to move away from that design choice because the framework prefers that.

You could rewrite some of the CSS to center the page or move the navigation to the top which would do the trick, but there is no built in way to do that.

**Comment by rrader** [comment]
I have nothing against left to right design. What I'm saying is that 100% width of the content block is actually not 100% but just about 800 pixels, so I can't have for example a table on full width of the screen.

Anyway, for everyone who also wants to do have this, I solved this by putting this to the stylesheet:

```
        .flakes-frame .flakes-navigation {
            width: 15%;
        }
        .flakes-frame .flakes-content {
            width: 85%;
        }

```
